# Generated by Django 4.2.4 on 2023-08-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
