# Generated by Django 4.2.4 on 2023-10-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_account_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pwd2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='pwd3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
