# Generated by Django 4.2.4 on 2023-08-28 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_is_ended_poll_has_ended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='description',
            new_name='desc',
        ),
    ]
