# Generated by Django 4.2.4 on 2023-08-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_account_phone_number_account_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='identifier',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
