# Generated by Django 4.2.4 on 2023-08-28 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_account_email_remove_account_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
