# Generated by Django 4.2.4 on 2023-08-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_account_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='used_vpn',
            field=models.BooleanField(default=False),
        ),
    ]
