# Generated by Django 4.2.4 on 2023-08-29 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_account_used_vpn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='_type',
            field=models.CharField(blank=True, choices=[('GM', 'Google'), ('IG', 'Instagram')], max_length=10, null=True),
        ),
    ]
